### ISSUE TITLE
Ability to change indicators for clarity

### ISSUE THREAD

**Issue by Gregovate** [tomvanswam/compass-card#1039]
**Is your feature request related to a problem? Please describe.**
I'm an active RV'r. A big problem we all have is protecting our awning during wind events. I have a LaCrosse breeze pro sensor I install on our roof after pulling into a new campsite. Using RTL433, I'm able to monitor the wind speed and direction.
I created a manual bearing sensor that I put in the bearing of our RV in the parked position. I know the position of our awning relative to our bearing. The "Danger Zone" in our case starts 30 degrees clockwise from our bearing and continues for an additional 90 degrees.  I'm currently a template sensor to calculate these positions.
```
- name: "Awning Danger Min"
    state: >
      {% set awning_dir_min = (states('input_number.campsite_bearing')|float) + 30 %}
      {%if awning_dir_min > 360 %}
        {% set awning_dir_min = awning_dir_min - 360 %}
      {% endif %} 
      {{ awning_dir_min }}
    unit_of_measurement: "Degrees"
    unique_id: 21fd871f

  - name: "Awning Danger Max"
    state: >
      {% set awning_dir_min = (states('input_number.campsite_bearing')|float) + 30 %}
      {% set awning_dir_max = awning_dir_min + 120 %}
      {%if awning_dir_max > 360 %}
        {% set awning_dir_min = awning_dir_max - 360 %}    
      {% endif %}  
      {{ awning_dir_max }}
    unit_of_measurement: "Degrees"
    unique_id: 3ee8f8c6
```

![Image](https://github.com/user-attachments/assets/160c11c1-a5ab-4610-8a68-971f982a2898)

I can tolerate higher wind speeds when the wind direction is not pointed into the danger zone. But Anything above 10 mph into the danger zone triggers an alert the awning must be taken in.

**Describe the solution you'd like**
I'm using the two outward arrows to indicate where the "Danger Zone" is located based on our current bearing. The inward arrow is the direction of the wind. It would be much clearer to have a red bar showing the Danger Zone

**Describe alternatives you've considered**
If there was a way to modify the colors of the arrows or replace them with different icons, that could work. The red dot shows our current bearing.

**Additional context**
Your card is great and wonderful visual to my screen! Keep up the good work!

**Comment by tomvanswam** [comment]
With version 3, you can now do this

<img width="468" height="528" alt="Image" src="https://github.com/user-attachments/assets/609992ee-f031-49ce-87ac-4c2058746139" />

With this yaml:
```yaml
type: custom:compass-card
indicator_sensors:
  - sensor: input_number.wind_direction_1
    indicator:
      image: arrow_inward
    state_abbreviation:
      show: false
  - sensor: input_number.nummer_2
    indicator:
      image: mdi:arrow-expand-right
      color: red
  - sensor: input_number.nummer_3
    indicator:
      image: mdi:arrow-expand-left
      color: red
value_sensors:
  - sensor: input_number.wind_speed
grid_options:
  columns: 12
  rows: 8
```
