### ISSUE TITLE
Hide direction abbreviation

### ISSUE THREAD

**Issue by tuxick** [tomvanswam/compass-card#115]
Would be nice to be able to not show direction abbreviation.Maybe by choosing no language? Or add "none"?

**Comment by tomvanswam** [comment]
From version 1.0.0 this is possible with YAML configuration:

Use the `state_abbreviation` key under the `indicator_sensor.sensor`
And set the `show` key to `false`.

Example:
```
type: custom:compass-card
header:
  title:
    value: Wind
indicator_sensors:
  - sensor: sensor.wind_dir
    indicator:
      type: arrow_inward
    state_abbreviation:
      show: false
value_sensors:
  - sensor: sensor.wind_speed
```
