### ISSUE TITLE
Feature request: Pointer colour based on wind speed

### ISSUE THREAD

**Issue by tomlut** [tomvanswam/compass-card#12]
**Is your feature request related to a problem? Please describe.**
No it is not related to a problem.

**Describe the solution you'd like**
It would be nice if the pointer colour was set by wind speed.  e.g. Define set points and colours like so:
```
color_thresholds:
  - color: '#e45e65'
    value: 30
  - color: '#e0b400'
    value: 20
  - color: '#0da035'
    value: 10
  - color: '#039BE5'
    value: 0
```
**Describe alternatives you've considered**
Honestly, it's just a "nice to have". Would not be fussed it if was beyond scope or put way down the bottom of the to-do list.

**Additional context**
Great card! Thanks.
