### ISSUE TITLE
Netatmo wind sensor probably not parsed correctly

### ISSUE THREAD

**Issue by matteofranceschini** [tomvanswam/compass-card#15]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
not relevant
**Last working release (if known):**

**Browser and Operating System:**
safari,chrome, homeassistant app, MacOs

**Description of problem:**

I have a Netatmo wind sensor, but the default HA integration provides the information with both text and degrees, for example like `W (240°)`, as shown in picture.

I think that there's a problem for the compass-card to parse this kind of information as, I assume, it expects just one of the two information and not both.

As you can see, it does not crash or anything, but obviously the arrow does not point in the correct direction!

<img width="365" alt="image" src="https://user-images.githubusercontent.com/3541957/90120544-2625df00-dd5b-11ea-9f5c-811edd93e425.png">
 For reference, this is the code that generates this card:

```
cards:
  - detail: 2
    entity: sensor.netatmo_jori_palace_anemogio_gust_strength
    graph: line
    name: Raffiche
    type: sensor
  - direction_offset: 0
    entity: sensor.netatmo_jori_palace_anemogio_angle
    name: Vento
    type: 'custom:compass-card'
    secondary_entity: sensor.netatmo_jori_palace_anemogio_wind_strength
type: horizontal-stack

```
I'm not fluent in javascript nor python, but i think that the problem could just be that the code just checks if the value given is NaN and does not search for a number in the string, to be parsed.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
If needed, I can do some testing.
