### ISSUE TITLE
Rotate North. Keep arrow up. Optional secondary arrow.

### ISSUE THREAD

**Issue by alnavasa** [tomvanswam/compass-card#155]
**Is your feature request related to a problem? Please describe.**
Used as a compass for a car, boat, or any moving vehicle.

**Describe the solution you'd like**
I would like to have a arrow pointing up, instead of the north, a north rotating, and if possible a second arrow pointing to the wind

**Describe alternatives you've considered**
I have tried to mess with the offset option, but couldn't make it work. Offset only allows values, not sensors, and I am neither sure if this would fix it.

**Additional context**
I have a wind direction sensor, a boat course, and a boat speed sensor, three sensors.
I would like to have it behave (Not look) like the two following:

<img width="277" alt="Captura de pantalla 2021-03-09 a las 21 01 55" src="https://user-images.githubusercontent.com/458370/110533726-955f8800-811e-11eb-84cb-63a9d79f1af6.png">
<img width="144" alt="Captura de pantalla 2021-03-09 a las 21 02 20" src="https://user-images.githubusercontent.com/458370/110533737-9690b500-811e-11eb-9673-9fa56a471a28.png">

Or if possible like this (arrow up, wind arrow, north rotating):

<img width="327" alt="Captura de pantalla 2021-03-09 a las 21 02 35" src="https://user-images.githubusercontent.com/458370/110533756-9abcd280-811e-11eb-90c1-fc670b1fd708.png">

**Comment by tomvanswam** [comment]
What an excellent idea! Thanks for taking the time to help make this card even better.

You're right, the N indicator can not be made dynamic with a sensor. I'll add this, and add E, S and W indicators as well.

Multiple arrows are already possible. I'll whip up an example and post it here.

**Comment by tomvanswam** [comment]
A kind of similar thing you ask for is possible, see the bottom right compass-card:
![image](https://user-images.githubusercontent.com/2330034/110626236-c4b6d900-81a0-11eb-8e9d-4e26d541f4cf.png)
The top right compass card shows the raw wind and heading angles.
Only thing that is not possible like this is to show the N as north indicator, that's why I configured it as outward arrow.

To get this you need 2 template sensors, which calculate the north and wind direction angle in relation to your heading.
```yaml
sensor:
  - platform: template
      calculated_north:
        friendly_name: "Calculated North"
        unit_of_measurement: "°"
        icon_template: "mdi:compass-outline"
        value_template: "{{ 360 - (states('input_number.heading') | float) }}"
      calculated_wind_direction:
        friendly_name: "Calculated Wind Direction"
        unit_of_measurement: "°"
        icon_template: "mdi:compass-outline"
        value_template: "{{ (states('input_number.wind_direction') | float) - (states('input_number.heading') | float) }}"
```

Use these sensors to populate the compass-card as such:
```yaml
type: 'custom:compass-card'
indicator_sensors:
  - sensor: sensor.calculated_north
    state_abbreviation:
      show: false
  - sensor: sensor.calculated_wind_direction
    indicator:
      type: inward
  - sensor: input_number.heading
    state_abbreviation:
      show: true
    state_value:
      show: true
    state_units:
      show: true
    indicator:
      show: false
```
Hope this will do until I get the N indicator also dynamic.

**Comment by alnavasa** [comment]
TOM! Thanks for considering the feature, 
I am not in a hurry, so I'll wait until v1.2
Thanks a lot!

**Comment by tomvanswam** [comment]
In v1.2.0 the background and e/s/w indicators are added. The dynamic N (and the other new ones ofc) will have to wait till v1.3.0

**Comment by alnavasa** [comment]
Don't worry tom! 
I'll try it, but looking forward for 1.3.0,
I am a fan of your work!
Thanks

**Comment by Psytoshgen** [comment]
Hi!
Can I take a little of your time? To not make new thread. Can you make offset option more friendly with direction?
Now it's looks like picture (my windows facing to south)
![12345676](https://user-images.githubusercontent.com/94195788/166654976-be071592-15b6-4c65-891c-c3fce05002a0.jpg)

**Comment by Psytoshgen** [comment]
> **Is your feature request related to a problem? Please describe.** Used as a compass for a car, boat, or any moving vehicle.
> 
> **Describe the solution you'd like** I would like to have a arrow pointing up, instead of the north, a north rotating, and if possible a second arrow pointing to the wind
> 
> **Describe alternatives you've considered** I have tried to mess with the offset option, but couldn't make it work. Offset only allows values, not sensors, and I am neither sure if this would fix it.
> 
> **Additional context** I have a wind direction sensor, a boat course, and a boat speed sensor, three sensors. I would like to have it behave (Not look) like the two following:
> 
> <img alt="Captura de pantalla 2021-03-09 a las 21 01 55" width="277" src="https://user-images.githubusercontent.com/458370/110533726-955f8800-811e-11eb-84cb-63a9d79f1af6.png">
> 
> <img alt="Captura de pantalla 2021-03-09 a las 21 02 20" width="144" src="https://user-images.githubusercontent.com/458370/110533737-9690b500-811e-11eb-9673-9fa56a471a28.png">
> 
> Or if possible like this (arrow up, wind arrow, north rotating):
> 
> <img alt="Captura de pantalla 2021-03-09 a las 21 02 35" width="327" src="https://user-images.githubusercontent.com/458370/110533756-9abcd280-811e-11eb-90c1-fc670b1fd708.png">

ah yes, maybe it's easy-to-use flexible horseshoe card integration to make last compas?

**Comment by tomvanswam** [comment]
> Hi! Can I take a little of your time? To not make new thread. Can you make offset option more friendly with direction? Now it's looks like picture (my windows facing to south)

Good point! Looks like a lazy implementation from my side ;-)

**Comment by tomvanswam** [comment]
Unfortunately not het, thanks for asking and reminding me ;-)

**Comment by tomerddd** [comment]
Heya! Wonder if you ever got to dynamic rotation (for boat heading)

Thanks for your efforts - love your work!

**Comment by tomvanswam** [comment]
I'm halfway there, but time is slipping through my fingers lately.

**Comment by Next9999** [comment]
i also look forward to have that nice feature :-)





![1](https://github.com/tomvanswam/compass-card/assets/54117519/73ca0788-65cd-4734-9122-ef06ea5e493e)

**Comment by Rust-Shch** [comment]
Hello! Sorry for may be stupid question, but how to include second stnsor into the compass? I want wind direction (arrow inward) and sun (when above horizon), with values of wind speed and azimuth, and house outline behind. So far I managed only wind and wind speed.
Thank you in advance and for the awesome instrument!

**Comment by tomvanswam** [comment]
> Hello! Sorry for may be stupid question, but how to include second stnsor into the compass? I want wind direction (arrow inward) and sun (when above horizon), with values of wind speed and azimuth, and house outline behind. So far I managed only wind and wind speed. Thank you in advance and for the awesome instrument!

With a config something like this
```yaml
type: 'custom:compass-card'
indicator_sensors:
  - sensor: sensor.wind
    indicator:
      type: inward
  - sensor: sensor.sun
    indicator:
      type: circle
```
