### ISSUE TITLE
Wind direction value format?

### ISSUE THREAD

**Issue by thehijacker** [tomvanswam/compass-card#196]
**Is your feature request related to a problem? Please describe.**
I am collecting wind speed from custom made wind station. I calculate wind direction inside the collection algorithm. It is displayed in HA with compass card but no translation language is working. I suspect bad value format.

**Describe the solution you'd like**
I wish to display wind direction in my language (Slovenian).

**Describe alternatives you've considered**
Well I need to know in what format must the wind direction entity be. Currently I store string value (W, S, E, N, SW, ...). Maybe it must be numeric (degrees)?.

**Additional context**
Here is the code that will calculate wind direction:

```
if(dirpin > 2.60 &&  dirpin < 2.70 ){
    wd = "E";
  }
  if(dirpin > 1.60 &&  dirpin < 1.70 ){
    wd = "SE";
  }
  if(dirpin > 0.30 &&  dirpin < 0.40 ){
    wd = "N";
  }
  if(dirpin > 0.60 &&  dirpin < 0.70 ){
    wd = "SW";
  }
  if(dirpin > 0.96 &&  dirpin < 1.06 ){
    wd = "W";
  }
  if(dirpin > 2.10 &&  dirpin < 2.20 ){
    wd = "NW";
  }
  if(dirpin > 3.15 &&  dirpin < 3.25 ){
    wd = "N";
  }
  if(dirpin > 2.95 &&  dirpin < 3.05 ){
    wd = "NE";
  }
```

Assembled my weather station by this guide:

https://tysonpower.de/blog/esp8266-weather-station

![image](https://user-images.githubusercontent.com/13857043/115985941-5e4e1480-a5ae-11eb-9f1d-778c20900746.png)

**Comment by tomvanswam** [comment]
You should be able to use
* numeric (in degrees, not radians or some other fancy system), the degrees can be positive or negative, they get calculated back to 0 to 360 degrees
* string with numeric value inside. 'NE 90' will get parsed to 90 degrees
* string, in english N, E, S and W, with up to 3 characters precision so NNE would work

So your string should work, however i might messed something up with the translation part.

What language do you have configured for the compass-card?

I'll have a look if I can find something broken.

**Comment by thehijacker** [comment]
I now send degree from 0 to 360 and string presentation and define it as sensor. In one I get N, S,... and with one I get value from 0 to 360. I still see only English translation. But only when direction is in degrees. If character they are in English only. Might be bug?

**Comment by thehijacker** [comment]
Maybe when defining sensors I need to define also value format? What I have so far:

```
  - platform: mqtt
    state_topic: 'weather_station/sensors'
    name: "Weather Station Wind Degree 2"
    value_template: '{{ value_json.winddegree2 | is_defined }}'
    expire_after: 21600 # 6 hours

  - platform: mqtt
    state_topic: 'weather_station/sensors'
    name: "Weather Station Wind Direction 2"
    value_template: '{{ value_json.winddirection2 | is_defined }}'
    expire_after: 21600 # 6 hours
```

When displaying this in compass card I get:

![image](https://user-images.githubusercontent.com/13857043/116004669-0e9a3800-a604-11eb-8cef-29fc88a9a355.png)

YAML code of this view:

```
cards:
  - cards:
      - class: top-level-graph
        type: 'custom:compass-card'
        indicator_sensors:
          - sensor: sensor.weather_station_wind_degree_2
            indicator:
              dynamic_style:
                sensor: sensor.weather_station_wind_speed
                bands:
                  - from_value: 0
                    color: '#039BE5'
                  - from_value: 10
                    color: '#0da035'
                  - from_value: 20
                    color: '#e0b400'
                  - from_value: 30
                    color: '#e45e65'
              type: arrow_outward
        value_sensors:
          - sensor: sensor.weather_station_wind_speed
        compass:
          north:
            show: false
        header:
          title:
            value: Degree
          icon:
            value: 'mdi:weather-windy'
            color: red
            dynamic_style:
              sensor: sensor.weather_station_wind_speed
              bands:
                - from_value: 0
                  color: green
                - from_value: 3
                  color: yellow
                - from_value: 6
                  color: orange
                - from_value: 8
                  color: red
                - from_value: 11
                  color: purple
        style: 'ha-card { height: 100%; }'
        language: sl
      - type: 'custom:compass-card'
        indicator_sensors:
          - sensor: sensor.weather_station_wind_direction_2
        value_sensors:
          - sensor: sensor.weather_station_wind_speed
        header:
          title:
            value: Textual direction
        language: sl
    type: horizontal-stack
  - type: entities
    entities:
      - entity: sensor.weather_station_wind_degree_2
      - entity: sensor.weather_station_wind_direction_2
type: vertical-stack
```

Let me know if you need any more additional data.

Thank you.
