### ISSUE TITLE
Translation of directions N-E-S-W

### ISSUE THREAD

**Issue by rainer-geiger** [tomvanswam/compass-card#22]
First off I want to say that this card is amazing! 

But I have a suggestion for improvement: Is it possible to introduce a translation of the "directional letters" in the configuration? I'm from Germany and in German for example "east" means "Osten". So it would be great if I could change the letters NESW according to my language.

Maybe something like this:

```
- compass:
          indicator: arrow_inward
          show_north: true
   direction_offset: 180
   entity: sensor.wind_bearing
   secondary_entity: sensor.wind_speed
   name: Wind
   translate:
          north: N
          east: O
          south: S
          west: W
   type: 'custom:compass-card'
```

**Comment by tomvanswam** [comment]
Thanks for your feedback!

I was planning on using the integrated translation in Home Assistant for translation, instead of putting translation in the yaml.

This would work for you when your Home Assistant language is set to German or to automatic and your browser sais to use German. If your configuration page is in German, your good.

I'd like to know if your Home Assistant is in German, and if you use a localized weather integration whether its string direction state has its states in German.

If you could find the time, could you help out translating the strings in [this](https://github.com/tomvanswam/compass-card/blob/master/src/localize/languages/en.json) file? Then all stuff will be in German.

**Comment by dhover** [comment]
I also would like to have the directions translated in Dutch. I' m using Home Assistant in English language because I like the original menu's and messages for troubleshooting.

**Comment by tomvanswam** [comment]
Ok good to know, so i would need to implement a forcing mechanism to pick a language different from the ui for the abbreviations.

**Comment by rainer-geiger** [comment]
Homeassistant is set to German. My weather integration is "DWD Deutscher Wetterdienst". The integration has no string direction state, only numerical value in degrees:

```
temperature: 21.5
humidity: 86
pressure: 1009.6
wind_bearing: 261
wind_speed: 1.5
visibility: 10.3
attribution: Data provided by Deutscher Wetterdienst (DWD)
forecast:
  - datetime: '2020-08-17'
    condition: lightning-rainy
    temperature: 22.4
    templow: 16.6
    precipitation: 7.4
    precipitation_probability: 71
  - [...]
latest_update_utc: '2020-08-17T10:02:55.370955+00:00'
forecast_time_utc: '2020-08-17T09:00:00+00:00'
station_id: EXXX
station_name: Wetter Zuhause
```


I've done the German translation, can I push it to dev?
