### ISSUE TITLE
Title does not follow the theme

### ISSUE THREAD

**Issue by matteofranceschini** [tomvanswam/compass-card#24]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
2.1
**Last working release (if known):**
0.0.5
**Browser and Operating System:**
safari macOs and iOS app

**Description of problem:**
The title does not follow the theme anymore (please see the "Vento" title WRT the "raffiche" title), I guess after version 0.1.0 included (but I'm not sure, haven't checked). I have all the titles in gray, only this one has changed.

Has something changed?

I have updated the theme "google light theme" to the latest version in the meantime, but this is the only card that has issues.

Screenshot of actual situation
<img width="367" alt="image" src="https://user-images.githubusercontent.com/3541957/90340510-03185b00-dff9-11ea-96ed-1694ed2bd702.png">

Screenshot from my "netatmo issue" on 0.0.5
![](https://user-images.githubusercontent.com/3541957/90120544-2625df00-dd5b-11ea-9f5c-811edd93e425.png)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by tomvanswam** [comment]
Is the graph in the screenshot a home assistant graph or a custom mini-graph-card?

I tried to make the title match the home assistand default cards, and in version 0.0.5 it was more like the mini-graph-card title (which did not match default home assistant cards).

I'll check with the google light theme if the card title keeps matching the default home assistant cards. I think I noticed the mini-graph-card titles not changing with a theme.

**Comment by matteofranceschini** [comment]
Sorry, I forgot to add the code! The graph is standard HA, just a plotted sensor.

```
cards:
  - detail: 2
    entity: sensor.netatmo_jori_palace_anemogio_gust_strength
    graph: line
    name: Raffiche
    type: sensor
  - compass:
      indicator: arrow_outward
      show_north: true
    direction_offset: 0
    entity: sensor.netatmo_jori_palace_anemogio_gust_angle
    name: Vento
    secondary_entity: sensor.netatmo_jori_palace_anemogio_wind_strength
    type: 'custom:compass-card'
type: horizontal-stack

```
I also have some _mini-graph-card_ cards, but in my deployment they seem to be compliant with the theme!

<img width="724" alt="image" src="https://user-images.githubusercontent.com/3541957/90344394-a9745880-e019-11ea-907c-edc15b2b87d6.png">

```
animate: true
cache: true
entities:
  - color: cyan
    entity: sensor.netatmo_taverna_co2
    name: Taverna
  - color: lightgreen
    entity: sensor.netatmo_jori_palace_interno_co2
    name: Fort Johns
hour24: true
hours_to_show: 168
font_size: 75
labels: true
show:
  average: true
  extrema: true
name: Anidride Carbonica
type: 'custom:mini-graph-card'

```
