### ISSUE TITLE
Style band object, allow hex colors

### ISSUE THREAD

**Issue by andilge** [tomvanswam/compass-card#409]
Hi Tom, I hope you started out well in 2022.

I wanted to set up a a wind compass using typical colors for the [beaufort scale](https://3.bp.blogspot.com/-RWFmqRl1l4Y/Vp0MPn7gbnI/AAAAAAAADog/dOsoeSJbs_M/s1600/BeaufortScale-page-0.jpg).

It appears color only accept strings, no hex codes, I wasn't able to set up the 12 colors as I wanted.

Is this me doing something wrong or could you please add support for hex colors? Here my unsuccessful lovalece yaml:

```yaml
type: custom:compass-card
header:
  title:
    value: Wind
  icon:
    color: '#d4d4d4'
    dynamic_style:
      sensor: sensor.weatherbit_beaufort
      bands:
        - from_value: 1
          color: '#cdfffe'
        - from_value: 2
          color: '#99ffcd'
        - from_value: 3
          color: '#99ff99'
        - from_value: 4
          color: '#98ff66'
        - from_value: 5
          color: '#9afe00'
        - from_value: 6
          color: '#ccff00'
        - from_value: 7
          color: '#ffff01'
        - from_value: 8
          color: '#ffcc00'
        - from_value: 9
          color: '#fe9900'
        - from_value: 10'
          color: '#ff6600'
        - from_value: 11
          color: '#ff3300'
        - from_value: 12
          color: '#fe0000'

**Comment by tomvanswam** [comment]
Hi andildge, thanks I did, I hope you did as well.

Your config only changes the icon color. And in my test env with this config:
```yaml
type: custom:compass-card
indicator_sensors:
  - sensor: input_number.wind
value_sensors:
  - sensor: input_number.wind
language: en
header:
  title:
    value: Wind
  icon:
    color: '#d4d4d4'
    dynamic_style:
      sensor: input_number.wind
      bands:
        - from_value: 1
          color: '#cdfffe'
        - from_value: 2
          color: '#99ffcd'
        - from_value: 3
          color: '#99ff99'
        - from_value: 4
          color: '#98ff66'
        - from_value: 5
          color: '#9afe00'
        - from_value: 6
          color: '#ccff00'
        - from_value: 7
          color: '#ffff01'
        - from_value: 8
          color: '#ffcc00'
        - from_value: 9
          color: '#fe9900'
        - from_value: 10'
          color: '#ff6600'
        - from_value: 11
          color: '#ff3300'
        - from_value: 12
          color: '#fe0000'
```

I do see a different icon color when changing the sensor value.

![image](https://user-images.githubusercontent.com/2330034/149568019-4276334b-e284-402d-b95d-267c32ce9988.png)

![image](https://user-images.githubusercontent.com/2330034/149568203-88c9773e-d547-4bd6-a2f6-dfbb58ed43ef.png)

![image](https://user-images.githubusercontent.com/2330034/149568239-4cc3bf2b-affe-4e8f-b8c7-d4ebdb54a677.png)

So I'm guessing something else is off. Might be your icon is invalid for the sensor. Or your sensor is not numerical perhaps, but string based.
If you want to have something else change color, you need to add the dynamic_styling to another key in the yaml.

You could post the output on the developer console in your browser when you add the `debug: true` config option. Maybe I can find something in there.

**Comment by andilge** [comment]
Goedenavond Tom,

Tnx for getting back so swiftly.

OK, you could successfully safe the lovelace card, I can't. This has nothing to do with the compass card, obviously another issue somewhere in HA.

I got insecure reading
https://github.com/tomvanswam/compass-card#style-band-object
but yeah, you just proven hex color codes are working. Maybe add a he color in the an example to prevent future questions like this?

Closing this PR since there's nothing to improve in the compass card. Again, tnx for all the efforts, very much appreciated.

**Comment by tomvanswam** [comment]
Well if your yaml is the complete one, it is missing the value and indicator node, might that be the reason you can't save it?

**Comment by andilge** [comment]
nah, it was wrong code in the lovelace card, my bad. Here the working example
```yaml
type: custom:compass-card
language: de
tap_action:
  action: more-info
  entity: sensor.weatherbit_wind_speed_km_h

header:
  title:
    value: Wind
  icon:
    color: '#777777'
    dynamic_style:
      sensor: sensor.weatherbit_beaufort
      bands:
        - from_value: 1
          color: '#cdfffe'
        - from_value: 2
          color: '#99ffcd'
        - from_value: 3
          color: '#99ff99'
        - from_value: 4
          color: '#98ff66'
        - from_value: 5
          color: '#9afe00'
        - from_value: 6
          color: '#ccff00'
        - from_value: 7
          color: '#ffff01'
        - from_value: 8
          color: '#ffcc00'
        - from_value: 9
          color: '#fe9900'
        - from_value: 10'
          color: '#ff6600'
        - from_value: 11
          color: '#ff3300'
        - from_value: 12
          color: '#fe0000'

value_sensors:
  - sensor: sensor.weatherbit_wind_speed_km_h
    decimals: 0

indicator_sensors:
  - sensor: sensor.weatherbit_wind_direction
    indicator:
      type: arrow_inward
      dynamic_style:
        sensor: sensor.weatherbit_wind_direction
        show: true

compass:
  north:
    color: '#777777'
    dynamic_style:
      sensor: sensor.weatherbit_beaufort
      bands:
        - from_value: 1
          color: #cdfffe
        - from_value: 2
          color: #99ffcd
        - from_value: 3
          color: #99ff99
        - from_value: 4
          color: #98ff66
        - from_value: 5
          color: #9afe00
        - from_value: 6
          color: #ccff00
        - from_value: 7
          color: #ffff01
        - from_value: 8
          color: #ffcc00
        - from_value: 9
          color: #fe9900
        - from_value: 10
          color: #ff6600
        - from_value: 11
          color: #ff3300
        - from_value: 12
          color: #fe0000

  circle:
    color: '#777777'
    dynamic_style:
      sensor: sensor.weatherbit_beaufort
      bands:
        - from_value: 1
          color: #cdfffe
        - from_value: 2
          color: #99ffcd
        - from_value: 3
          color: #99ff99
        - from_value: 4
          color: #98ff66
        - from_value: 5
          color: #9afe00
        - from_value: 6
          color: #ccff00
        - from_value: 7
          color: #ffff01
        - from_value: 8
          color: #ffcc00
        - from_value: 9
          color: #fe9900
        - from_value: 10
          color: #ff6600
        - from_value: 11
          color: #ff3300
        - from_value: 12
          color: #fe0000
```
