### ISSUE TITLE
Change color

### ISSUE THREAD

**Issue by pex81** [tomvanswam/compass-card#412]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**
Firefox and Home Assistant 2021.12.9

**Description of problem:**
Is it possible to change the color of the ENE writing?

![immagine](https://user-images.githubusercontent.com/58252398/149770220-31d415b1-4550-4879-bfc0-bf3058895743.png)

this is my code:
```
          type: custom:compass-card      
          indicator_sensors:
            - sensor: sensor.meteo
              attribute: wind_direction
              indicator:
                color: rgba(255,255,255,0.8)
          value_sensors:
            - sensor: sensor.meteo
              attribute: wind_speed
          compass:        
            language: it
            circle:
              color: rgba(255, 255, 255, 0.8)                       
            north:
              show: true
              color: rgba(255, 255, 255, 0.8)
            east:
              show: true
              color: rgba(255, 255, 255, 0.8)              
            west:
              show: true
              color: rgba(255, 255, 255, 0.8)              
            south:
              show: true  
              color: rgba(255, 255, 255, 0.8) 
```

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by tomvanswam** [comment]
Change your indicator_sensor to:
```yaml
            - sensor: sensor.meteo
              attribute: wind_direction
              indicator:
                color: rgba(255,255,255,0.8)
              state_abbreviation:
                color: rgba(255,255,255,0.8)
```
And the abbreviation will be the same color as the other objects.
