### ISSUE TITLE
display direction in degrees

### ISSUE THREAD

**Issue by think-nice-things** [tomvanswam/compass-card#48]
**Is your feature request related to a problem? Please describe.**
I didn't manage to display the direction in degrees instead of something like SW.
All example images in https://github.com/tomvanswam/compass-card show the direction as SW, there's no example which shows the direction as degrees.

**Describe the solution you'd like**
I'd like to have an option to display the direction in degrees.
I didn't find any option to do so.

**Comment by tomvanswam** [comment]
Thanks for using the card!

There is a lot of config possible from version 1 on, and I tried to document it as good as I could, however I can understand someone might miss something.

With version 1 you can configure the card like you specified.
Use this config:
```
type: 'custom:compass-card'
indicator_sensors:
  - sensor: input_number.wind_direction
    state_value:
      show: true
    state_units:
      show: true
    state_abbreviation:
      show: false
```

To get this result:
![192 168 2 50_8123_lovelace_v100-alpha3](https://user-images.githubusercontent.com/2330034/100602788-a9684200-3304-11eb-80f9-ea8b553d7189.png)

For the first direction sensor, only the abbreviation is shown by default.
To show the value and units, you should enable them in yaml (and if you want to hide the abbreviation, hide that)
Every next direction sensor has value, units and abbreviation hidden by default, but they can also be made visible by using the same config.

Hope this helps
