### ISSUE TITLE
Index 16 is not displaying North

### ISSUE THREAD

**Issue by baunan** [tomvanswam/compass-card#62]
Hi, 

First thanks for a very usefull card. I have an issue with it when the wind direction is close to North, e.g. 351°. When the direction is in this region the wind direction abbrivation disapare rather than displaying North as it should do by the intension of the code. Direction 351° should give an index of 16 which should show N.

```
  static getCompassAbbreviation(degrees: number, language: string | undefined): string {
    const index = Math.round(CompassCard.positiveDegrees(degrees) / 22.5);
    let string = 'N';
    if (index > 15) {
      string = COMPASS_ABBREVIATIONS[0];
    }
```

![image](https://user-images.githubusercontent.com/59838425/101983703-0ce75d80-3c7d-11eb-94e9-be390b9d5242.png)
![image](https://user-images.githubusercontent.com/59838425/101983814-98f98500-3c7d-11eb-8059-f102e9c104da.png)

I am not sure whats wrong, but it would be good if it could be fixed.

I am running v1.0 of the card and the fault was also present on the previous versions.

**Comment by tomvanswam** [comment]
I'll have a look, thanks for opening the issue!

**Comment by tomvanswam** [comment]
@baunan could you paste your complete compass-card config please?

**Comment by baunan** [comment]
Sorry, should have done that in the first place.

```
type: 'custom:compass-card'
indicator_sensors:
  - sensor: sensor.hytta_retning
    indicator:
      type: arrow_inward
value_sensors:
  - sensor: sensor.hytta_retning
language: 'no'
tap_action:
  entity: sensor.hytta_retning
header:
  title:
    value: Vindretning
```
