### ISSUE TITLE
Two enhancement suggestions

### ISSUE THREAD

**Issue by txNgineer** [tomvanswam/compass-card#792]
I am using the card on my Lovelace dashboard and am very pleased with it and its current customizations. There are two things that would enhance my layout if you ever have time to consider it. 

First, I would like to be able to control the size of the indicator icon somewhat. In my case where it is a wind direction indicator, it would be a bit better if it were larger. Second, I would like to be able to move the direction text (e.g., "SE 135") below the wind speed text.

Here is my Lovelace code:
```
type: custom:compass-card
header:
  title:
    value: Wind
indicator_sensors:
  - sensor: sensor.openweathermap_wind_bearing
    indicator:
      type: arrow_inward
    state_value:
      show: true
    state_units:
      show: true
value_sensors:
  - sensor: sensor.wind_speed_mph
compass:
  north:
    show: true
```
Note that I did a value template to convert the openweathermap_wind_speed from m/s to the "uncouth" MPH.

**Comment by tomvanswam** [comment]
Your second request will probably be possible in v3+.  
You'll need card-mod to configure this, but in order to be able to change the order with card-mod, the card has been updated.

Check flex box row order css examples how to get this done

Changing the size of embedded indicators will be added in v3.1.0

**Comment by tomvanswam** [comment]
With v3.0.0 the following is possible:

<img width="481" height="516" alt="Image" src="https://github.com/user-attachments/assets/fa263570-59d8-4eab-8e16-6eb5647ad1d8" />

With this code:
```yaml
type: custom:compass-card
indicator_sensors:
  - sensor: input_number.wind_direction_1
    indicator:
      image: /local/images/person.png
      size: 30
      radius: 90
  - sensor: input_text.wind_direction_2
    indicator:
      image: /local/images/cloud-bolt-solid-full.svg
      size: 20
      radius: 50
  - sensor: input_text.wind_direction_2
    indicator:
      image: mdi:weather-sunset-down
      size: 10
      radius: 80
      color: "#ff00ff"
value_sensors:
  - sensor: input_number.wind_speed
grid_options:
  columns: 12
  rows: 8
card_mod:
  style: |
    ha-card .indicator-sensor.sensor-0 {
      order: 2 !important;
    }
    ha-card .value-sensor.sensor-0 {
      order: 1 !important;
    }
```

You do need [card-mod](https://github.com/thomasloven/lovelace-card-mod) for this to work
