### ISSUE TITLE
tap_action

### ISSUE THREAD

**Issue by CHORCHES** [tomvanswam/compass-card#829]
Good day....
Use type: custom:compass-card mounted on type: custom:state-switch...
I need "tap_action" to work:"action:toggle"
Thank you

**Comment by tomvanswam** [comment]
When I get to it, I'll try to implement it.

**Comment by CHORCHES** [comment]
Thank you, Tom.

**Comment by vingerha** [comment]
I suggest to drop this as there is a service call implemented which can handle that. example:
```
tap_action:
  action: call-service
  service: homeassistant.toggle
  service_data: '{entity_id": "input_boolean.test_toggle"}'
```
