### ISSUE TITLE
Set image ( entity_picture_template ) as indicator type

### ISSUE THREAD

**Issue by ggonmar** [tomvanswam/compass-card#873]
I have been playing with this card, and it would be neat if I could use my sensor of the moon, which has a custom image of the current state of the moon (within the property `entity_picture_template`) , as the icon of the compass.

I'd envision it as:

```
type: custom:compass-card
header:
  title:
    value: Moon
indicator_sensors:
  - sensor: sensor.moon_phase
    attribute: azimuth
    indicator:
      type: image
      image: sensor.moon_phase
value_sensors:
  - sensor: sun.sun
    attribute: elevation
```

That would be very nice!

Thanks for your great work!
