### ISSUE TITLE
FR: Wind Direction Arrow in center of the card

### ISSUE THREAD

**Issue by jimz011** [tomvanswam/compass-card#885]
It would be amazing if we can have the arrow in the center of the card (and possibly have a slightly bigger arrow when doing so).

This card is almost perfect to fit my own dashboard, the 2 things missing are a bigger arrow and an arrow in the center.

I would like to mimic the Google Weather application and this card seems the only one even getting close.

Example below:
![image](https://github.com/tomvanswam/compass-card/assets/47046878/8b3ddce9-4932-46e4-bdb0-3ee118b1d98d)

Thanks for this amazing card.

**Comment by tomvanswam** [comment]
Sounds like a lot of work, but might be doable. I'll look into it, on how to implement this without creating a more configuration madness.

**Comment by tomvanswam** [comment]
In v3.0.0 you can do this:

<img width="484" height="195" alt="Image" src="https://github.com/user-attachments/assets/50d1bd8b-d1f5-4976-b469-7e292b76b46d" />

With this configuration:
```yaml
type: custom:compass-card
indicator_sensors:
  - sensor: sun.sun
    attribute: azimuth
    indicator:
      image: mdi:arrow-up-bold
      size: 150
      radius: 0
    state_abbreviation:
      show: false
```
