### ISSUE TITLE
Number of decimals shown

### ISSUE THREAD

**Issue by oywino** [tomvanswam/compass-card#891]
I display a wind speed sensor with i.e the value 8,33 m/s and it doesn't show the decimals, only the integer value:
What am I doing wrong:
![image](https://github.com/user-attachments/assets/6ccdd065-2833-4aa9-9d28-eb944beb5550)

**Comment by tomvanswam** [comment]
Use the YAML config and add the decimals setting to the value_sensor.

```yaml
value_sensors:
  - sensor: sensor.wind_speed
    decimals: 2
```
