### ISSUE TITLE
Direction not shown correctly (Netatmo)

### ISSUE THREAD

**Issue by dabenzel** [tomvanswam/compass-card#895]
**Checklist:**

- [x ] I updated to the latest version available
- [x ] I cleared the cache of my browser

**Release with the issue:**
Compass-Card 2.0.0 / HomeAssistant 2024.8 and 2024.9

**Last working release (if known):**

**Browser and Operating System:**

Arc (also HASS-APP on iOS18), Windows

**Description of problem:**

Direction not correctly shown in Card.
![image](https://github.com/user-attachments/assets/639ba923-2a3c-42cd-9203-d2f171c288f1)

**Javascript errors shown in the web inspector (if applicable):**
Appears after some time
```
compass-card.js?hacstag=286038496200:70 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'attributes')
    at compass-card.js?hacstag=286038496200:70:24775
    at ti (compass-card.js?hacstag=286038496200:70:25337)
    at header.entities.i (compass-card.js?hacstag=286038496200:1043:3064)
    at qn.updateConfig (compass-card.js?hacstag=286038496200:1043:3482)
    at set hass (compass-card.js?hacstag=286038496200:1043:1518)
    at i.value (hui-card.ts:99:21)
    at i.value (hui-card.ts:155:18)
    at i.performUpdate (reactive-element.ts:1329:14)
    at i.scheduleUpdate (reactive-element.ts:1261:17)
    at i._$Ej (reactive-element.ts:1233:25)
```

**YAML config or the card with the bug:**

```yaml
type: custom:compass-card
indicator_sensors:
  - sensor: sensor.windmesser_direction
value_sensors:
  - sensor: sensor.windmesser_gust_strength
header:
  title:
    value: Wind
language: en

```

**Screenshots of the Developer Tools page, State tab:**
![image](https://github.com/user-attachments/assets/172c720a-f9d6-4331-85e2-f5adda353cda)

```yaml
options:
  - "n"
  - ne
  - e
  - se
  - s
  - sw
  - w
  - nw
attribution: Data provided by Netatmo
device_class: enum
friendly_name: Windmesser Windrichtung

```

**Additional information:**
```json
{
    "sensor.windmesser_direction": {
        "entity_id": "sensor.windmesser_direction",
        "state": "ne",
        "attributes": {
            "options": [
                "n",
                "ne",
                "e",
                "se",
                "s",
                "sw",
                "w",
                "nw"
            ],
            "attribution": "Data provided by Netatmo",
            "device_class": "enum",
            "friendly_name": "Windmesser Windrichtung"
        },
        "context": {
            "id": "xxxxx",
            "parent_id": null,
            "user_id": null
        },
        "last_changed": "2024-09-05T11:45:18.888Z",
        "last_updated": "2024-09-05T11:45:18.888Z"
    },
    "sensor.windmesser_gust_strength": {
        "entity_id": "sensor.windmesser_gust_strength",
        "state": "16",
        "attributes": {
            "state_class": "measurement",
            "unit_of_measurement": "km/h",
            "attribution": "Data provided by Netatmo",
            "device_class": "wind_speed",
            "friendly_name": "Windmesser Böenstärke"
        },
        "context": {
            "id": "xxxxxx",
            "parent_id": null,
            "user_id": null
        },
        "last_changed": "2024-09-05T12:22:18.420Z",
        "last_updated": "2024-09-05T12:22:18.420Z"
    }
}
```
